name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  run-tests:
    runs-on: ${{ needs.build.outputs.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build CMake Project
        uses: ./.github/workflows/CMake-Build.yml

      - name: Run tests
        if: startsWith(needs.build.outputs.os, 'Windows')
        working-directory: ${{ needs.build.outputs.build-output-dir }}/Bardrix_Tests/${{ needs.build.outputs.build_type }}
        run: |
          Bardrix_Tests.exe

      - name: Run tests
        if: startsWith(needs.build.outputs.os, 'Ubuntu')
        working-directory: ${{ needs.build.outputs.build-output-dir }}/Bardrix_Tests/
        run: |
          ./Bardrix_Tests
