name: Examples Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    uses: ./.github/workflows/Build-Test-Cmake.yml
    with:
      os: ${{ matrix.os }}
      source_directory: "Docs/Examples"