name: Examples Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    uses: ./.github/workflows/Build-Test-Cmake.yml
    with:
      source_directory: "Docs/Examples"